#!/bin/bash 
#docker-compose -f poolnet.yml -f docker-compose.yml up -d !/bin/bash
cd /home/deploy/backup
docker save pool:v30 | pv -s $(docker image inspect pool:v30 --format='{{.Size}}') | gzip > pool-image.tgz


#$SHELL
